import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import SplashCursor from "@/components/SplashCursor/Index";
import AntdRegistry from "@/components/AntdRegistry/Index";

import ThemeProvider from "@/components/ThemeProvider/Index";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-100`}
        >
          <ThemeProvider>
            {/* 解决ssr阶段样式闪烁 */}
            <AntdRegistry>
              <SplashCursor />
              {/* 内容宽度 */}
              <div className="p-4 md:p-0">
                {/* 内容 */}
                <main>{children}</main>
              </div>
            </AntdRegistry>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
